### ISSUE TITLE
lose the first few frame when use your stitch code

### ISSUE THREAD

**Issue by notedit** [carsonmcdonald/iOSVideoCameraMultiStitchExample#1]
hi  i does not use your whole code.  i use the GPUImage to record some video and use your AVAssetStitcher code to combine them. but i found that the first few frame sometimes is lost, there is a black frame in their.  

i do not know the reason, can you give me some advice?

**Comment by carsonmcdonald** [comment]
Can you describe the steps you are using to create the video with GPUImage or do you have sample code somewhere that you are using?

**Comment by notedit** [comment]
i use this GPUImage's pull request from this https://github.com/BradLarson/GPUImage/pull/835,  it can pause/resume the video record.  i write a new file when the app become active from background, there is only one file if the app does not into the background.   then i will combine these files into one file using your AVAssetStitcher.

this demo app works well in the past weekend,  but today i found  the final video  lose some the first few frame.

**Comment by notedit** [comment]
another question about your code is that if i pause too many times, it will generate so many tmpfile, the combining will take too long.  

there is an article about this http://www.gdcl.co.uk//2013/03/22/iPhone-Resume-Recording.html.

**Comment by carsonmcdonald** [comment]
I will try to take a look at the missing frames issue but my guess is that it is the technique used to generated the segments and not the stitching them together part. My initial guess is that the times are getting mangled somehow and the combining part doesn't know how to handle it past dropping the frames.

If you want to open another issue on things being slow that would be fine, if you would include the hardware you have tested on and the number of videos that start making things slow. I have it on a short list of TODOs to see if I can speed it up but there are a few other issues I want to address first. I'm not sure that I want to do what is being done in the link above or not. It may end up being impossible to do it any differently than that but I want to try and work within the confines of combining files if I can.

**Comment by notedit** [comment]
ok  i will fork your repo to see whether  i can make some improvments.

**Comment by RoCry** [comment]
Sometime i have the problem too..
Haven't figured out yet...

**Comment by carsonmcdonald** [comment]
There was an issue with setting the frameDuration that may have been causing this issue, that should be fixed in 453ed27c003d29da9bad6160471b948e02a5bd62 so if someone who has seen this wants to give the latest a try and re-open if it is still an issue.
