### ISSUE TITLE
Never worked for me.

### ISSUE THREAD

**Issue by instantback** [carsonmcdonald/iOSVideoCameraMultiStitchExample#3]
I always get a "Can't finalize recording unless all sub-recordings are finished." or other errors. What's the problem?
Thank you.

**Comment by Reefaq** [comment]
This error is thrown when you are finalizing video while recording is going on. Check the flag _inFlightWrites_, it gets incremented while recording is started and decremented at finish. 

Give a try to recheck with your integration.
