### ISSUE TITLE
IOS7 issue

### ISSUE THREAD

**Issue by VladManolache** [carsonmcdonald/iOSVideoCameraMultiStitchExample#6]
Thanks for a cool library.

Have you tried it with IOS7? I'm getting only a single frame for the duration of the video.

In - (void)exportTo:(NSURL *)outputFile withPreset:(NSString *)preset withCompletionHandler:(void (^)(NSError *error))completionHandler

I've set videoComposition.frameDuration = CMTimeMake(1, 30); and this seems to fix things.

**Comment by antonioparisi** [comment]
+1

**Comment by carsonmcdonald** [comment]
This should be fixed now with 453ed27c003d29da9bad6160471b948e02a5bd62
